# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1dbd93c4aec438ab2eef3aeae0cf382e628374539a27707a205d82ae9e69f9ae8f1e48dddbd521b2d241bbb5daf2367766dfff8c5a4e1469a1f9e199effba10

test:
  secret_key_base: cf567ef5b7f04b855470ed4b432b6bd3ba09b862970f4e58cf3e3620c8e879b0942dac383f24371bb236acd02aaddd2985c7a29ea45e164d695c4c7214b1d4c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
